<template>
  <div>
    <v-tabs v-model="tab" class="mb-4"><v-tab value="source">Sources</v-tab><v-tab value="overlay">Overlays</v-tab><v-tab value="audio">Audio</v-tab></v-tabs>
    <v-window v-model="tab">
      <v-window-item value="source"><div class="yolobox-grid"><v-card v-for="s in directors" :key="s.id" class="cursor-pointer" :variant="s.isSelected?'elevated':'tonal'" @click="emit('command','yolobox.execute',{data:{id:s.id,isSelected:true},orderID:'order_director_change'})"><v-img v-if="s.previewUrl||s.url" :src="s.previewUrl||s.url" aspect-ratio="16/9" cover/><v-card-text class="text-center">{{ s.directorName||s.name||s.id }}</v-card-text></v-card></div></v-window-item>
      <v-window-item value="overlay"><div class="yolobox-grid"><v-card v-for="m in materials" :key="m.id" class="cursor-pointer" :variant="m.isSelected?'elevated':'tonal'" @click="emit('command','yolobox.execute',{data:{id:m.id,isSelected:false},orderID:'order_material_change'})"><v-img v-if="m.previewUrl||m.url" :src="m.previewUrl||m.url" aspect-ratio="16/9" cover/></v-card></div></v-window-item>
      <v-window-item value="audio"><v-list bg-color="transparent"><v-list-item v-for="a in mixer" :key="a.id" :title="a.name||a.audioName||a.id"><template #append><v-slider class="yolobox-mixer-slider" :model-value="Number(a.volume??0)" min="0" max="1" :step="Number(a.steps_range??a.step_range??.05)" hide-details @end="(v:any)=>emit('command','yolobox.execute',{data:{id:a.id,isSelected:a.isSelected,volume:Number(v),AFV:a.AFV??a.afv??false,delayTime:a.delayTime??0},orderID:'order_mixer_change'})"/></template></v-list-item></v-list></v-window-item>
    </v-window>
  </div>
</template>
<script setup lang="ts">import{computed,ref,watch}from'vue';const props=defineProps<{yolobox:any}>();const emit=defineEmits<{command:[method:string,params:any]}>();const tab=ref('source');watch(tab,v=>{const map:any={audio:4,overlay:1,source:2};emit('command','yolobox.execute',{data:{id:map[v]},orderID:'order_tab_change'})});const data=computed(()=>props.yolobox?.data??{});const directors=computed(()=>data.value.DirectorList??[]);const materials=computed(()=>data.value.MaterialList??[]);const mixer=computed(()=>data.value.MixerList??[])</script>
